# Constants....

PORT = 8080
IP_SERVER = '35.175.203.232'

# server constants
ENCONDING_FORMAT = "utf-8"
RECV_BUFFER_SIZE = 1024

# tpp methods
REGISTER = 'REGISTER'
CREATE = 'CREATE'
JOIN = 'JOIN'
START = 'START'
POST_STATE = 'POST_STATE'
GET_STATE = 'GET_STATE'
QUIT = 'QUIT'
SUCC = 'SUCC'
ERR = 'ERR'
